# Generated by Django 3.1 on 2020-08-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200819_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drug'),
        ),
    ]
