# Generated by Django 3.1 on 2020-09-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_drug_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='tag',
        ),
    ]
